name: Deploy develop
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Init project
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db
      - name: PHP Linter
        uses: michaelw90/PHP-Lint@master
      - name: Security checker
        uses: symfonycorp/security-checker-action@v2
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse src/ --level=5
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
        with:
          file_or_dir: config/.
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_DEVELOP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          procfile: "web: heroku-php-apache2 public/"
